apiVersion: v1
kind: ServiceAccount
metadata:
  name: udp-listener
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: udp-listener
  labels:
    app: udp-listener
spec:
  replicas: 1
  selector:
    matchLabels:
      app: udp-listener
  template:
    metadata:
      labels:
        app: udp-listener
    spec:
      nodeSelector:
        node-role.kubernetes.io/worker-apps: demo
      containers:
        - name: udp-listener
          image: mendhak/udp-listener
          ports:
            - containerPort: 5005
              protocol: UDP
              name: udp
          resources:
            limits:
              cpu: '1'
              memory: '512Mi'
            requests:
              cpu: '0.5'
              memory: '256Mi'
---
apiVersion: v1
kind: Service
metadata:
  name: udp-listener
spec:
  ports:
    - port: 5005
      targetPort: 5005
      protocol: UDP
      name: udp
  selector:
    app: udp-listener
