apiVersion: 'ingresstcp.k8s.f5net.com/v1'
kind: F5SPKIngressTCP
metadata:
  name: onlineboutique
  namespace: demoapp
service:
  name: frontend-external
  port: 80
spec:
  destinationAddress: 10.1.10.202
  destinationPort: 80
  idleTimeout: 30
  loadBalancingMethod: 'ROUND_ROBIN'
  vlans:
    vlanList:
      - external
    disableListedVlans: false
monitors:
  tcp:
    - interval: 3
    - timeout: 10
